# Generated by Django 5.1.4 on 2025-01-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
