# Generated by Django 5.1.4 on 2025-01-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
