# Generated by Django 5.1.4 on 2025-01-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_profile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
