# Generated by Django 5.1.4 on 2025-01-21 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.tasklist'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='color',
            field=models.CharField(choices=[('#FF5733', 'Red'), ('#33FF57', 'Green'), ('#3357FF', 'Blue'), ('#FFFF33', 'Yellow'), ('#FF33FF', 'Pink'), ('#33FFFF', 'Cyan')], default='#FFFFFF', max_length=7),
        ),
    ]
